#!/bin/sh


tmux split-window -h 
tmux split-window -v 35
tmux selectp -t 0
tmux send-keys "nvim $1" enter
tmux selectp -t 1
tmux send-keys "bin/webpack-dev-server" enter
tmux split-window -v
tmux split-window -h
tmux selectp 3
tmux send-keys "rails s" enter
tmux break-pane

tmux select-window -t 0
tmux selectp 3

tmux send-keys 'open http://localhost:3000' enter
